service: ecom-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: java17
  region: ${env:AWS_REGION}

  deploymentBucket:
    name: ${env:AWS_DEPLOY_BUCKET}

package:
  artifact: target/ecomserverless-dev.jar

functions:
  payu-payments:
    handler: com.serverless.handlers.CashfreeUWebhookHandler

    events:
      - httpApi:
          path: /cashfree/payments
          method: post

    environment:
      KAFKA_REST_URL: ${env:KAFKA_REST_URL}
      KAFKA_USERNAME: ${env:KAFKA_USERNAME}
      KAFKA_PASSWORD: ${env:KAFKA_PASSWORD}
      CASHFREE_WEBHOOK_KAFKA_TOPIC_NAME: ${env:CASHFREE_WEBHOOK_KAFKA_TOPIC_NAME}
